import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter, Roboto_Mono, Playfair_Display } from "next/font/google";

const playfairDisplay = Playfair_Display({
  weight: ["400", "700"], // You can specify font weights you need
  subsets: ["latin"], // Specify the subset (e.g., latin, cyrillic)
  variable: "--font-playfair-display",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${roboto_mono.variable}  ${playfairDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
